language: python
python:
  - "3.7"
dist: trusty
addons:
  sonarcloud:
    organization: "jeffgreenca-github"
install:
  - pip install tox-travis
script:
  - tox -e lint-check
  - sonar-scanner
  - tox
